-- =============================================
-- 1. GEOGRAPHY (CITIES & STREETS)
-- =============================================

CREATE TABLE IF NOT EXISTS CITIES (
                        CITY_ID INTEGER NOT NULL,
                        NAME    VARCHAR2(100 CHAR) NOT NULL,
                        PSC     VARCHAR2(6 CHAR) NOT NULL,
                        CONSTRAINT CITY_PK PRIMARY KEY (CITY_ID),
                        CONSTRAINT CITY_NAME_PSC_UN UNIQUE (NAME, PSC),
                        CONSTRAINT CITY_PSC_CK CHECK (REGEXP_LIKE(PSC, '^\d{3}\s\d{2}$'))
);
/

CREATE TABLE IF NOT EXISTS STREETS (
                         STREET_ID INTEGER NOT NULL,
                         NAME      VARCHAR2(100 CHAR) NOT NULL,
                         CITY_ID   INTEGER NOT NULL,
                         CONSTRAINT STREET_PK PRIMARY KEY (STREET_ID),
                         CONSTRAINT STREET_NAME_CITY_UN UNIQUE (NAME, CITY_ID),
                         CONSTRAINT STREET_CITY_FK FOREIGN KEY (CITY_ID) REFERENCES CITIES (CITY_ID)
);
/

CREATE TABLE IF NOT EXISTS ADDRESSES (
                           ADDRESS_ID         INTEGER NOT NULL,
                           HOUSE_NUMBER       VARCHAR2(10 CHAR) NOT NULL,
                           STREET_ID          INTEGER NOT NULL,
                           CONSTRAINT ADDRESS_PK PRIMARY KEY (ADDRESS_ID),
                           CONSTRAINT ADDRESS_STREET_FK FOREIGN KEY (STREET_ID) REFERENCES STREETS (STREET_ID),
                           CONSTRAINT ADDRESS_NUM_UN UNIQUE (HOUSE_NUMBER, STREET_ID),
                           CONSTRAINT CHK_HOUSE_NUMBER_FORMAT
                                CHECK (REGEXP_LIKE(HOUSE_NUMBER, '^[1-9][0-9]{0,3}(/[1-9][0-9]{0,3}[a-z]?)?$'))
);
/

-- =============================================
-- 2. USERS
-- =============================================

CREATE TABLE IF NOT EXISTS USERS (
                       USER_ID          INTEGER NOT NULL,
                       EMPLOYEE_ID      VARCHAR2(20 CHAR) NOT NULL UNIQUE, -- For login
                       PASSWORD_HASH    VARCHAR2(255 CHAR) NOT NULL,
                       FIRST_NAME       VARCHAR2(50 CHAR) NOT NULL,
                       LAST_NAME        VARCHAR2(50 CHAR) NOT NULL,
                       USER_TYPE        VARCHAR2(20 CHAR) NOT NULL,
                       PHONE            VARCHAR2(20 CHAR) NOT NULL,
                       EMAIL            VARCHAR2(254 CHAR) NOT NULL UNIQUE,
                       IS_ACTIVE        NUMBER(1) DEFAULT 1 NOT NULL,
                       VERSION          INTEGER DEFAULT 0 NOT NULL,
                       CONSTRAINT USER_PK PRIMARY KEY (USER_ID),
                       CONSTRAINT USER_ID_TYPE_UN UNIQUE (USER_ID, USER_TYPE),
                       CONSTRAINT CHK_USER_TYPE CHECK (USER_TYPE IN ('ADMIN', 'ADVISOR')),
                       CONSTRAINT CHK_USER_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);
/

CREATE TABLE IF NOT EXISTS ADVISORS (
                          USER_ID          INTEGER NOT NULL,
                          USER_TYPE        VARCHAR2(20 CHAR) DEFAULT 'ADVISOR' NOT NULL,
                          ICO              VARCHAR2(8 CHAR) NOT NULL UNIQUE,
                          MANAGER_ID       INTEGER,
                          CONSTRAINT ADVISOR_PK PRIMARY KEY (USER_ID),
                          CONSTRAINT ADVISOR_TYPE_CHK CHECK (USER_TYPE = 'ADVISOR'),
                          CONSTRAINT ADVISOR_ICO_CK CHECK (REGEXP_LIKE(ICO, '^[[:digit:]]{8}$')),
                          CONSTRAINT ADVISOR_MANAGER_FK FOREIGN KEY (MANAGER_ID) REFERENCES ADVISORS (USER_ID),
                          CONSTRAINT ADVISOR_USER_FK FOREIGN KEY (USER_ID, USER_TYPE)
                              REFERENCES USERS (USER_ID, USER_TYPE) ON DELETE CASCADE
);
/

-- =============================================
-- 3. CORE DOMAIN (CLIENTS & ASSETS)
-- =============================================

CREATE TABLE IF NOT EXISTS CLIENTS (
                         CLIENT_ID           INTEGER NOT NULL,
                         CLIENT_UID          VARCHAR2(8 CHAR) NOT NULL UNIQUE,
                         PERSONAL_ID         VARCHAR2(10 CHAR) NOT NULL,
                         BIRTH_DATE          DATE NOT NULL,
                         LAST_NAME           VARCHAR2(50 CHAR) NOT NULL,
                         FIRST_NAME          VARCHAR2(50 CHAR) NOT NULL,
                         PHONE               VARCHAR2(20 CHAR) NOT NULL,
                         EMAIL               VARCHAR2(254 CHAR),
                         ID_CARD_NUMBER      VARCHAR(9 CHAR) NOT NULL,
                         ID_CARD_ISSUE_DATE  DATE NOT NULL,
                         ID_CARD_EXPIRY_DATE DATE NOT NULL,
                         ID_CARD_ISSUER      VARCHAR2(100 CHAR) NOT NULL,
                         LAST_UPDATE         DATE NOT NULL,
                         ADVISOR_ID          INTEGER NOT NULL,
                         PERMANENT_ADDR_ID   INTEGER NOT NULL,
                         CONTACT_ADDR_ID     INTEGER NOT NULL,
                         VERSION             INTEGER DEFAULT 0 NOT NULL,
                         IS_ACTIVE           NUMBER(1) DEFAULT 1 NOT NULL,
                         CONSTRAINT CLIENT_PK PRIMARY KEY (CLIENT_ID),
                         CONSTRAINT CLIENT_PERSONAL_ID_UN UNIQUE (PERSONAL_ID),
                         CONSTRAINT CLIENT_ID_CARD_UN UNIQUE (ID_CARD_NUMBER),
                         CONSTRAINT CLIENT_PERSONAL_ID_CK CHECK (REGEXP_LIKE(PERSONAL_ID, '^[[:digit:]]{10}$')),
                         CONSTRAINT CLIENT_ID_CARD_CK CHECK (REGEXP_LIKE(ID_CARD_NUMBER, '^[[:digit:]]{9}$')),
                         CONSTRAINT CLIENT_EXPIRY_CK CHECK (ID_CARD_EXPIRY_DATE > ID_CARD_ISSUE_DATE),
                         CONSTRAINT CLIENT_ADVISOR_FK FOREIGN KEY (ADVISOR_ID) REFERENCES ADVISORS (USER_ID),
                         CONSTRAINT CLIENT_PERM_ADDR_FK FOREIGN KEY (PERMANENT_ADDR_ID) REFERENCES ADDRESSES (ADDRESS_ID),
                         CONSTRAINT CLIENT_CONT_ADDR_FK FOREIGN KEY (CONTACT_ADDR_ID) REFERENCES ADDRESSES (ADDRESS_ID),
                         CONSTRAINT CLIENT_ACTIVE_CK CHECK (IS_ACTIVE IN (0, 1))
);
/

CREATE TABLE IF NOT EXISTS ASSET_TYPES (
                             ASSET_TYPE_ID INTEGER NOT NULL,
                             NAME          VARCHAR2(50 CHAR) NOT NULL,
                             CONSTRAINT ASSET_TYPE_PK PRIMARY KEY (ASSET_TYPE_ID),
                             CONSTRAINT ASSET_TYPE_NAME_UN UNIQUE (NAME)
);
/

CREATE TABLE IF NOT EXISTS ASSETS (
                        ASSET_ID      INTEGER NOT NULL,
                        NAME          VARCHAR2(100 CHAR) NOT NULL,
                        VALUE         INTEGER NOT NULL,
                        NOTE          VARCHAR2(256 CHAR),
                        ASSET_TYPE_ID INTEGER NOT NULL,
                        CLIENT_ID     INTEGER NOT NULL,
                        CONSTRAINT ASSET_PK PRIMARY KEY (ASSET_ID),
                        CONSTRAINT ASSET_VALUE_CK CHECK (VALUE BETWEEN 1 AND 999999999),
                        CONSTRAINT ASSET_TYPE_FK FOREIGN KEY (ASSET_TYPE_ID) REFERENCES ASSET_TYPES (ASSET_TYPE_ID),
                        CONSTRAINT ASSET_CLIENT_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (CLIENT_ID) ON DELETE CASCADE
);
/

-- =============================================
-- 4. BUDGET (INCOMES & EXPENSES)
-- =============================================

CREATE TABLE IF NOT EXISTS INCOME_TYPES (
                              INCOME_TYPE_ID  INTEGER NOT NULL,
                              NAME            VARCHAR2(50 CHAR) NOT NULL,
                              CONSTRAINT INCOME_TYPE_PK PRIMARY KEY (INCOME_TYPE_ID),
                              CONSTRAINT INCOME_TYPE_NAME_UN UNIQUE (NAME)
);
/

CREATE TABLE IF NOT EXISTS INCOMES (
                         INCOME_ID      INTEGER NOT NULL,
                         AMOUNT         INTEGER NOT NULL,
                         CLIENT_ID      INTEGER NOT NULL,
                         INCOME_TYPE_ID INTEGER NOT NULL,
                         VERSION        INTEGER DEFAULT 0 NOT NULL,
                         CONSTRAINT INCOME_PK PRIMARY KEY (INCOME_ID),
                         CONSTRAINT INCOME_AMOUNT_CK CHECK (AMOUNT BETWEEN 1 AND 999999999),
                         CONSTRAINT INCOME_CLIENT_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (CLIENT_ID) ON DELETE CASCADE,
                         CONSTRAINT INCOME_TYPE_FK FOREIGN KEY (INCOME_TYPE_ID) REFERENCES INCOME_TYPES (INCOME_TYPE_ID)
);
/

CREATE TABLE IF NOT EXISTS EXPENSE_TYPES (
                               EXPENSE_TYPE_ID INTEGER NOT NULL,
                               NAME            VARCHAR2(50 CHAR) NOT NULL,
                               CONSTRAINT EXPENSE_TYPE_PK PRIMARY KEY (EXPENSE_TYPE_ID),
                               CONSTRAINT EXPENSE_TYPE_NAME_UN UNIQUE (NAME)
);
/

CREATE TABLE IF NOT EXISTS EXPENSES (
                          EXPENSE_ID      INTEGER NOT NULL,
                          AMOUNT          INTEGER NOT NULL,
                          IS_MANDATORY    NUMBER(1) DEFAULT 0 NOT NULL,
                          CLIENT_ID       INTEGER NOT NULL,
                          EXPENSE_TYPE_ID INTEGER NOT NULL,
                          VERSION         INTEGER DEFAULT 0 NOT NULL,
                          CONSTRAINT EXPENSE_PK PRIMARY KEY (EXPENSE_ID),
                          CONSTRAINT EXPENSE_AMOUNT_CK CHECK (AMOUNT BETWEEN 1 AND 999999999),
                          CONSTRAINT EXPENSE_MANDATORY_CK CHECK (IS_MANDATORY IN (0, 1)),
                          CONSTRAINT EXPENSE_CLIENT_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (CLIENT_ID) ON DELETE CASCADE,
                          CONSTRAINT EXPENSE_TYPE_FK FOREIGN KEY (EXPENSE_TYPE_ID) REFERENCES EXPENSE_TYPES (EXPENSE_TYPE_ID)
);
/

-- =============================================
-- 5. PRODUCTS & PROVIDERS
-- =============================================

CREATE TABLE IF NOT EXISTS PROVIDERS (
                           PROVIDER_ID INTEGER NOT NULL,
                           NAME        VARCHAR2(100 CHAR) NOT NULL,
                           CONSTRAINT PROVIDER_PK PRIMARY KEY (PROVIDER_ID),
                           CONSTRAINT PROVIDER_NAME_UN UNIQUE (NAME)
);
/

CREATE TABLE IF NOT EXISTS PRODUCT_TYPES (
                               PRODUCT_TYPE_ID INTEGER NOT NULL,
                               NAME            VARCHAR2(50 CHAR) NOT NULL,
                               CONSTRAINT PRODUCT_TYPE_PK PRIMARY KEY (PRODUCT_TYPE_ID),
                               CONSTRAINT PRODUCT_TYPE_NAME_UN UNIQUE (NAME)
);
/

CREATE TABLE IF NOT EXISTS PRODUCTS (
                  PRODUCT_ID         INTEGER NOT NULL,
                  NAME               VARCHAR2(150 CHAR) NOT NULL,
                  AMOUNT             NUMBER(10,2) NOT NULL,
                  START_DATE         DATE NOT NULL,
                  END_DATE           DATE,
                  PRODUCT_TYPE_ID    INTEGER NOT NULL,
                  CLIENT_ID          INTEGER NOT NULL,
                  PROVIDER_ID        INTEGER NOT NULL,
                  MANAGED_BY_ID      INTEGER,
                  NEXT_ANNIVERSARY   DATE NOT NULL,
                  CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID),
                  CONSTRAINT PRODUCT_AMOUNT_CK CHECK (AMOUNT BETWEEN 0.00 AND 99999999.99),
                  CONSTRAINT PRODUCT_DATES_CK CHECK (END_DATE IS NULL OR END_DATE > START_DATE),
                  CONSTRAINT PRODUCT_CLIENT_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (CLIENT_ID) ON DELETE CASCADE,
                  CONSTRAINT PRODUCT_TYPE_FK FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPES (PRODUCT_TYPE_ID),
                  CONSTRAINT PRODUCT_PROVIDER_FK FOREIGN KEY (PROVIDER_ID) REFERENCES PROVIDERS (PROVIDER_ID),
                  CONSTRAINT PRODUCT_ADVISOR_FK FOREIGN KEY (MANAGED_BY_ID) REFERENCES ADVISORS (USER_ID)
);
/

-- =============================================
-- 6. DOCUMENTS
-- =============================================

CREATE TABLE IF NOT EXISTS DOCUMENT_TYPES (
                                DOCUMENT_TYPE_ID INTEGER NOT NULL,
                                NAME             VARCHAR2(50 CHAR) NOT NULL,
                                CONSTRAINT DOCUMENT_TYPE_PK PRIMARY KEY (DOCUMENT_TYPE_ID),
                                CONSTRAINT DOCUMENT_TYPE_NAME_UN UNIQUE (NAME)
);
/

CREATE TABLE IF NOT EXISTS DOCUMENTS (
           DOCUMENT_ID      INTEGER NOT NULL,
           FILE_NAME        VARCHAR2(255 CHAR) NOT NULL,
           FILE_PATH        VARCHAR2(512 CHAR) NOT NULL,
           UPLOADED_AT      DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
           DOCUMENT_TYPE_ID INTEGER NOT NULL,
           CLIENT_ID        INTEGER NOT NULL,
           PRODUCT_ID       INTEGER,
           VERSION       INTEGER DEFAULT 0 NOT NULL,
           CONSTRAINT DOCUMENT_PK PRIMARY KEY (DOCUMENT_ID),
           CONSTRAINT DOCUMENT_TYPE_FK FOREIGN KEY (DOCUMENT_TYPE_ID) REFERENCES DOCUMENT_TYPES (DOCUMENT_TYPE_ID),
           CONSTRAINT DOCUMENT_CLIENT_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (CLIENT_ID) ON DELETE CASCADE,
           CONSTRAINT DOCUMENT_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID) ON DELETE CASCADE
);
/

-- =============================================
-- 7. VIEWS
-- =============================================

CREATE OR REPLACE VIEW V_CLIENT_SEARCH_MINIMAL AS
SELECT
    C.CLIENT_ID,
    C.ADVISOR_ID,
    C.PERSONAL_ID,
    C.FIRST_NAME || ' ' || C.LAST_NAME AS FULL_NAME,
    CI_P.NAME AS PERM_CITY_NAME,
    CI_P.PSC AS PERM_PSC
FROM CLIENTS C
         JOIN ADDRESSES A_P ON C.PERMANENT_ADDR_ID = A_P.ADDRESS_ID
         JOIN STREETS ST_P ON A_P.STREET_ID = ST_P.STREET_ID
         JOIN CITIES CI_P ON ST_P.CITY_ID = CI_P.CITY_ID;
/

-- =============================================
-- 8. TRIGGERS (BUSINESS LOGIC)
-- =============================================

CREATE OR REPLACE TRIGGER TRG_ADDRESSES_BU
BEFORE UPDATE ON ADDRESSES
FOR EACH ROW
BEGIN
    raise_application_error(-20011, 'Address records are immutable. Create a new record for changes (PP11).');
END;
/

CREATE OR REPLACE TRIGGER TRG_CLIENTS_BIU
BEFORE INSERT OR UPDATE ON CLIENTS
FOR EACH ROW
DECLARE
    v_adv_active NUMBER(1);
BEGIN
    :NEW.LAST_UPDATE := TRUNC(SYSDATE);
    IF :NEW.BIRTH_DATE > ADD_MONTHS(TRUNC(SYSDATE), -12*18) THEN
        raise_application_error(-20012, 'Client must be at least 18 years old (PP12).');
    END IF;
    IF INSERTING OR (UPDATING AND :NEW.ADVISOR_ID <> :OLD.ADVISOR_ID) THEN
        SELECT IS_ACTIVE INTO v_adv_active FROM USERS WHERE USER_ID = :NEW.ADVISOR_ID;
        IF v_adv_active = 0 THEN
            raise_application_error(-20013, 'Cannot assign an inactive advisor to a client.');
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ADVISORS_BIU
BEFORE INSERT OR UPDATE ON ADVISORS
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.MANAGER_ID IS NOT NULL THEN
        raise_application_error(-20002, 'A new advisor cannot have a manager assigned immediately (PP02).');
    END IF;
    IF :NEW.MANAGER_ID = :NEW.USER_ID THEN
        raise_application_error(-20010, 'An advisor cannot be their own manager (PP10).');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_INCOMES_BIU
BEFORE INSERT OR UPDATE ON INCOMES
FOR EACH ROW
DECLARE
    v_client_active NUMBER(1);
BEGIN
    IF INSERTING OR (UPDATING AND :NEW.CLIENT_ID <> :OLD.CLIENT_ID) THEN
        SELECT IS_ACTIVE INTO v_client_active FROM CLIENTS WHERE CLIENT_ID = :NEW.CLIENT_ID;
        IF v_client_active = 0 THEN
            raise_application_error(-20016, 'Cannot add an income to an inactive client.');
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PRODUCTS_BI
BEFORE INSERT ON PRODUCTS
FOR EACH ROW
DECLARE
    v_expiry DATE;
    v_current_adv INTEGER;
    v_client_active NUMBER(1);
    v_manager_active NUMBER(1);
BEGIN
    SELECT ID_CARD_EXPIRY_DATE, ADVISOR_ID, IS_ACTIVE
    INTO v_expiry, v_current_adv, v_client_active
    FROM CLIENTS WHERE CLIENT_ID = :NEW.CLIENT_ID;

    IF v_client_active = 0 THEN
        raise_application_error(-20014, 'Cannot arrange product: Client is inactive.');
    END IF;
    IF v_expiry < SYSDATE THEN
        raise_application_error(-20001, 'Cannot arrange product: Client ID card expired (PP01).');
    END IF;
    IF :NEW.MANAGED_BY_ID IS NOT NULL THEN
        IF v_current_adv <> :NEW.MANAGED_BY_ID THEN
            raise_application_error(-20004, 'The arranger must be the client current advisor (PP04).');
        END IF;

        SELECT IS_ACTIVE INTO v_manager_active FROM USERS WHERE USER_ID = :NEW.MANAGED_BY_ID;
        IF v_manager_active = 0 THEN
             raise_application_error(-20015, 'Cannot assign an inactive advisor to manage a product.');
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ASSETS_BIU
BEFORE INSERT OR UPDATE ON ASSETS
FOR EACH ROW
DECLARE
    v_client_active NUMBER(1);
BEGIN
    IF INSERTING OR (UPDATING AND :NEW.CLIENT_ID <> :OLD.CLIENT_ID) THEN
        SELECT IS_ACTIVE INTO v_client_active FROM CLIENTS WHERE CLIENT_ID = :NEW.CLIENT_ID;
        IF v_client_active = 0 THEN
            raise_application_error(-20017, 'Cannot add an asset to an inactive client.');
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_EXPENSES_BIU
BEFORE INSERT OR UPDATE ON EXPENSES
FOR EACH ROW
DECLARE
    v_client_active NUMBER(1);
BEGIN
    IF INSERTING OR (UPDATING AND :NEW.CLIENT_ID <> :OLD.CLIENT_ID) THEN
        SELECT IS_ACTIVE INTO v_client_active FROM CLIENTS WHERE CLIENT_ID = :NEW.CLIENT_ID;
        IF v_client_active = 0 THEN
            raise_application_error(-20018, 'Cannot add an expense to an inactive client.');
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_DOCUMENTS_BIU
BEFORE INSERT OR UPDATE ON DOCUMENTS
FOR EACH ROW
DECLARE
    v_client_active NUMBER(1);
BEGIN
    IF INSERTING OR (UPDATING AND :NEW.CLIENT_ID <> :OLD.CLIENT_ID) THEN
        SELECT IS_ACTIVE INTO v_client_active FROM CLIENTS WHERE CLIENT_ID = :NEW.CLIENT_ID;
        IF v_client_active = 0 THEN
            raise_application_error(-20019, 'Cannot attach a document to an inactive client.');
        END IF;
    END IF;
END;
/

-- =============================================
-- 9. FOREIGN KEY INDEXES (Performance)
-- =============================================

CREATE INDEX IF NOT EXISTS IDX_STREET_CITY_FK      ON STREETS (CITY_ID);
/
CREATE INDEX IF NOT EXISTS IDX_ADDRESS_STREET_FK   ON ADDRESSES (STREET_ID);
/
CREATE INDEX IF NOT EXISTS IDX_CLIENT_ADVISOR_FK   ON CLIENTS (ADVISOR_ID);
/
CREATE INDEX IF NOT EXISTS IDX_CLIENT_PERM_ADDR_FK ON CLIENTS (PERMANENT_ADDR_ID);
/
CREATE INDEX IF NOT EXISTS IDX_CLIENT_CONT_ADDR_FK ON CLIENTS (CONTACT_ADDR_ID);
/
CREATE INDEX IF NOT EXISTS IDX_ADVISOR_USER_FK    ON ADVISORS (USER_ID, USER_TYPE);
/
CREATE INDEX IF NOT EXISTS IDX_ADVISOR_MANAGER_FK ON ADVISORS (MANAGER_ID);
/
CREATE INDEX IF NOT EXISTS IDX_ASSET_CLIENT_FK    ON ASSETS (CLIENT_ID);
/
CREATE INDEX IF NOT EXISTS IDX_ASSET_TYPE_FK      ON ASSETS (ASSET_TYPE_ID);
/
CREATE INDEX IF NOT EXISTS IDX_INCOME_CLIENT_FK   ON INCOMES (CLIENT_ID);
/
CREATE INDEX IF NOT EXISTS IDX_INCOME_TYPE_FK     ON INCOMES (INCOME_TYPE_ID);
/
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_CLIENT_FK  ON EXPENSES (CLIENT_ID);
/
CREATE INDEX IF NOT EXISTS IDX_EXPENSE_TYPE_FK    ON EXPENSES (EXPENSE_TYPE_ID);
/
CREATE INDEX IF NOT EXISTS IDX_PRODUCT_CLIENT_FK  ON PRODUCTS (CLIENT_ID);
/
CREATE INDEX IF NOT EXISTS IDX_PRODUCT_TYPE_FK    ON PRODUCTS (PRODUCT_TYPE_ID);
/
CREATE INDEX IF NOT EXISTS IDX_PRODUCT_PROVIDER_FK ON PRODUCTS (PROVIDER_ID);
/
CREATE INDEX IF NOT EXISTS IDX_PRODUCT_MANAGER_FK  ON PRODUCTS (MANAGED_BY_ID);
/
CREATE INDEX IF NOT EXISTS IDX_DOCUMENT_TYPE_FK    ON DOCUMENTS (DOCUMENT_TYPE_ID);
/
CREATE INDEX IF NOT EXISTS IDX_DOCUMENT_CLIENT_FK  ON DOCUMENTS (CLIENT_ID);
/
CREATE INDEX IF NOT EXISTS IDX_DOCUMENT_PRODUCT_FK ON DOCUMENTS (PRODUCT_ID);
/

-- =============================================
-- 10. SEARCH INDEXES (User Experience)
-- =============================================

CREATE INDEX IF NOT EXISTS IDX_CLIENT_LAST_FIRST  ON CLIENTS (LAST_NAME, FIRST_NAME);
/
CREATE INDEX IF NOT EXISTS IDX_ADVISOR_LAST_FIRST ON USERS (LAST_NAME, FIRST_NAME);
/

-- =============================================
-- 11. ID GENERATION (SEQUENCES & AUTO-INC)
-- =============================================

CREATE SEQUENCE IF NOT EXISTS BUDGET_ITEM_SEQ START WITH 1 NOCACHE ORDER;
/

CREATE OR REPLACE TRIGGER TRG_INCOMES_ID BEFORE INSERT ON INCOMES FOR EACH ROW WHEN (NEW.INCOME_ID IS NULL)
BEGIN :NEW.INCOME_ID := BUDGET_ITEM_SEQ.NEXTVAL; END;
/

CREATE OR REPLACE TRIGGER TRG_EXPENSES_ID BEFORE INSERT ON EXPENSES FOR EACH ROW WHEN (NEW.EXPENSE_ID IS NULL)
BEGIN :NEW.EXPENSE_ID := BUDGET_ITEM_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE IF NOT EXISTS CITY_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_CITY_ID BEFORE INSERT ON CITIES FOR EACH ROW WHEN (NEW.CITY_ID IS NULL) BEGIN :NEW.CITY_ID := CITY_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE IF NOT EXISTS STREET_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_STREET_ID BEFORE INSERT ON STREETS FOR EACH ROW WHEN (NEW.STREET_ID IS NULL) BEGIN :NEW.STREET_ID := STREET_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE IF NOT EXISTS ADDR_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_ADDR_ID BEFORE INSERT ON ADDRESSES FOR EACH ROW WHEN (NEW.ADDRESS_ID IS NULL) BEGIN :NEW.ADDRESS_ID := ADDR_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE IF NOT EXISTS USER_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_USER_ID BEFORE INSERT ON USERS FOR EACH ROW WHEN (NEW.USER_ID IS NULL) BEGIN :NEW.USER_ID := USER_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE IF NOT EXISTS CLIENT_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_CLIENT_ID BEFORE INSERT ON CLIENTS FOR EACH ROW WHEN (NEW.CLIENT_ID IS NULL) BEGIN :NEW.CLIENT_ID := CLIENT_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE IF NOT EXISTS ASSET_TYPE_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_ASSET_TYPE_ID BEFORE INSERT ON ASSET_TYPES FOR EACH ROW WHEN (NEW.ASSET_TYPE_ID IS NULL) BEGIN :NEW.ASSET_TYPE_ID := ASSET_TYPE_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE IF NOT EXISTS ASSET_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_ASSET_ID BEFORE INSERT ON ASSETS FOR EACH ROW WHEN (NEW.ASSET_ID IS NULL) BEGIN :NEW.ASSET_ID := ASSET_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE IF NOT EXISTS INCOME_TYPE_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_INCOME_TYPE_ID BEFORE INSERT ON INCOME_TYPES FOR EACH ROW WHEN (NEW.INCOME_TYPE_ID IS NULL) BEGIN :NEW.INCOME_TYPE_ID := INCOME_TYPE_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE IF NOT EXISTS EXPENSE_TYPE_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_EXPENSE_TYPE_ID BEFORE INSERT ON EXPENSE_TYPES FOR EACH ROW WHEN (NEW.EXPENSE_TYPE_ID IS NULL) BEGIN :NEW.EXPENSE_TYPE_ID := EXPENSE_TYPE_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE IF NOT EXISTS PROVIDER_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_PROVIDER_ID BEFORE INSERT ON PROVIDERS FOR EACH ROW WHEN (NEW.PROVIDER_ID IS NULL) BEGIN :NEW.PROVIDER_ID := PROVIDER_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE IF NOT EXISTS PRODUCT_TYPE_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_PRODUCT_TYPE_ID BEFORE INSERT ON PRODUCT_TYPES FOR EACH ROW WHEN (NEW.PRODUCT_TYPE_ID IS NULL) BEGIN :NEW.PRODUCT_TYPE_ID := PRODUCT_TYPE_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE IF NOT EXISTS PRODUCT_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_PRODUCT_ID BEFORE INSERT ON PRODUCTS FOR EACH ROW WHEN (NEW.PRODUCT_ID IS NULL) BEGIN :NEW.PRODUCT_ID := PRODUCT_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE IF NOT EXISTS DOCUMENT_TYPE_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_DOCUMENT_TYPE_ID BEFORE INSERT ON DOCUMENT_TYPES FOR EACH ROW WHEN (NEW.DOCUMENT_TYPE_ID IS NULL) BEGIN :NEW.DOCUMENT_TYPE_ID := DOCUMENT_TYPE_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE IF NOT EXISTS DOCUMENT_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_DOCUMENT_ID BEFORE INSERT ON DOCUMENTS FOR EACH ROW WHEN (NEW.DOCUMENT_ID IS NULL) BEGIN :NEW.DOCUMENT_ID := DOCUMENT_SEQ.NEXTVAL; END;
/