-- =============================================
-- 1. GEOGRAPHY (CITIES & STREETS)
-- =============================================

CREATE TABLE CITIES (
                        CITY_ID INTEGER NOT NULL,
                        NAME    VARCHAR2(100 CHAR) NOT NULL,
                        PSC     NUMBER(5) NOT NULL,
                        CONSTRAINT CITY_PK PRIMARY KEY (CITY_ID),
                        CONSTRAINT CITY_PSC_CK CHECK (PSC BETWEEN 10000 AND 99999),
                        CONSTRAINT CITY_NAME_PSC_UN UNIQUE (NAME, PSC)
);
/

CREATE TABLE STREETS (
                         STREET_ID INTEGER NOT NULL,
                         NAME      VARCHAR2(100 CHAR) NOT NULL,
                         CITY_ID   INTEGER NOT NULL,
                         CONSTRAINT STREET_PK PRIMARY KEY (STREET_ID),
                         CONSTRAINT STREET_NAME_CITY_UN UNIQUE (NAME, CITY_ID),
                         CONSTRAINT STREET_CITY_FK FOREIGN KEY (CITY_ID) REFERENCES CITIES (CITY_ID)
);
/

-- =============================================
-- 2. INFRASTRUCTURE (ADDRESSES & ADVISORS)
-- =============================================

CREATE TABLE ADDRESSES (
                           ADDRESS_ID         INTEGER NOT NULL,
                           HOUSE_NUMBER       NUMBER(4) NOT NULL,
                           ORIENTATION_NUMBER NUMBER(4),
                           STREET_ID          INTEGER NOT NULL,
                           CONSTRAINT ADDRESS_PK PRIMARY KEY (ADDRESS_ID),
                           CONSTRAINT ADDRESS_STREET_FK FOREIGN KEY (STREET_ID) REFERENCES STREETS (STREET_ID),
                           CONSTRAINT ADDRESS_NUM_UN UNIQUE (HOUSE_NUMBER, ORIENTATION_NUMBER, STREET_ID)
);
/

CREATE TABLE ADVISORS (
                          ADVISOR_ID       INTEGER NOT NULL,
                          ICO              VARCHAR2(8 CHAR) NOT NULL,
                          LAST_NAME        VARCHAR2(50 CHAR) NOT NULL,
                          FIRST_NAME       VARCHAR2(50 CHAR) NOT NULL,
                          PASSWORD_HASH    NVARCHAR2(254) NOT NULL,
                          PHONE            VARCHAR2(20 CHAR) NOT NULL,
                          EMAIL            VARCHAR2(254 CHAR) NOT NULL,
                          MANAGER_ID       INTEGER,
                          CONSTRAINT ADVISOR_PK PRIMARY KEY (ADVISOR_ID),
                          CONSTRAINT ADVISOR_ICO_UN UNIQUE (ICO),
                          CONSTRAINT ADVISOR_ICO_CK CHECK (REGEXP_LIKE(ICO, '^[[:digit:]]{8}$')),
                          CONSTRAINT ADVISOR_MANAGER_FK FOREIGN KEY (MANAGER_ID) REFERENCES ADVISORS (ADVISOR_ID)
);
/

-- =============================================
-- 3. CORE DOMAIN (CLIENTS & ASSETS)
-- =============================================

CREATE TABLE CLIENTS (
                         CLIENT_ID           INTEGER NOT NULL,
                         PERSONAL_ID         VARCHAR2(10 CHAR) NOT NULL,
                         BIRTH_DATE          DATE NOT NULL,
                         LAST_NAME           VARCHAR2(50 CHAR) NOT NULL,
                         FIRST_NAME          VARCHAR2(50 CHAR) NOT NULL,
                         PHONE               VARCHAR2(20 CHAR) NOT NULL,
                         EMAIL               VARCHAR2(254 CHAR),
                         ID_CARD_NUMBER      NUMBER(9) NOT NULL,
                         ID_CARD_ISSUE_DATE  DATE NOT NULL,
                         ID_CARD_EXPIRY_DATE DATE NOT NULL,
                         ID_CARD_ISSUER      VARCHAR2(100 CHAR) NOT NULL,
                         ID_CARD_COPY_URL    VARCHAR2(256 CHAR) NOT NULL,
                         LAST_UPDATE         DATE NOT NULL,
                         ADVISOR_ID          INTEGER NOT NULL,
                         PERMANENT_ADDR_ID   INTEGER NOT NULL,
                         CONTACT_ADDR_ID     INTEGER NOT NULL,
                         CONSTRAINT CLIENT_PK PRIMARY KEY (CLIENT_ID),
                         CONSTRAINT CLIENT_PERSONAL_ID_UN UNIQUE (PERSONAL_ID),
                         CONSTRAINT CLIENT_ID_CARD_UN UNIQUE (ID_CARD_NUMBER),
                         CONSTRAINT CLIENT_PERSONAL_ID_CK CHECK (REGEXP_LIKE(PERSONAL_ID, '^[[:digit:]]{10}$')),
                         CONSTRAINT CLIENT_ID_CARD_CK CHECK (ID_CARD_NUMBER BETWEEN 100000000 AND 999999999),
                         CONSTRAINT CLIENT_EXPIRY_CK CHECK (ID_CARD_EXPIRY_DATE > ID_CARD_ISSUE_DATE),
                         CONSTRAINT CLIENT_ADVISOR_FK FOREIGN KEY (ADVISOR_ID) REFERENCES ADVISORS (ADVISOR_ID),
                         CONSTRAINT CLIENT_PERM_ADDR_FK FOREIGN KEY (PERMANENT_ADDR_ID) REFERENCES ADDRESSES (ADDRESS_ID),
                         CONSTRAINT CLIENT_CONT_ADDR_FK FOREIGN KEY (CONTACT_ADDR_ID) REFERENCES ADDRESSES (ADDRESS_ID)
);
/

CREATE TABLE ASSET_TYPES (
                             ASSET_TYPE_ID INTEGER NOT NULL,
                             NAME          VARCHAR2(50 CHAR) NOT NULL,
                             CONSTRAINT ASSET_TYPE_PK PRIMARY KEY (ASSET_TYPE_ID),
                             CONSTRAINT ASSET_TYPE_NAME_UN UNIQUE (NAME)
);
/

CREATE TABLE ASSETS (
                        ASSET_ID      INTEGER NOT NULL,
                        NAME          VARCHAR2(100 CHAR) NOT NULL,
                        VALUE         INTEGER NOT NULL,
                        NOTE          VARCHAR2(256 CHAR),
                        ASSET_TYPE_ID INTEGER NOT NULL,
                        CLIENT_ID     INTEGER NOT NULL,
                        CONSTRAINT ASSET_PK PRIMARY KEY (ASSET_ID),
                        CONSTRAINT ASSET_VALUE_CK CHECK (VALUE BETWEEN 1 AND 999999999),
                        CONSTRAINT ASSET_TYPE_FK FOREIGN KEY (ASSET_TYPE_ID) REFERENCES ASSET_TYPES (ASSET_TYPE_ID),
                        CONSTRAINT ASSET_CLIENT_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (CLIENT_ID) ON DELETE CASCADE
);
/

-- =============================================
-- 4. BUDGET (INCOMES & EXPENSES)
-- =============================================

CREATE SEQUENCE BUDGET_ITEM_SEQ START WITH 1 NOCACHE ORDER;
/

CREATE TABLE INCOME_TYPES (
                              INCOME_TYPE_ID  INTEGER NOT NULL,
                              NAME            VARCHAR2(50 CHAR) NOT NULL,
                              IS_ASSET_LINKED NUMBER(1) DEFAULT 0 NOT NULL,
                              CONSTRAINT INCOME_TYPE_PK PRIMARY KEY (INCOME_TYPE_ID),
                              CONSTRAINT INCOME_TYPE_LINK_CK CHECK (IS_ASSET_LINKED IN (0, 1)),
                              CONSTRAINT INCOME_TYPE_NAME_UN UNIQUE (NAME)
);
/

CREATE TABLE INCOMES (
                         INCOME_ID      INTEGER NOT NULL,
                         AMOUNT         INTEGER NOT NULL,
                         CLIENT_ID      INTEGER NOT NULL,
                         INCOME_TYPE_ID INTEGER NOT NULL,
                         ASSET_ID       INTEGER,
                         CONSTRAINT INCOME_PK PRIMARY KEY (INCOME_ID),
                         CONSTRAINT INCOME_AMOUNT_CK CHECK (AMOUNT BETWEEN 1 AND 999999999),
                         CONSTRAINT INCOME_CLIENT_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (CLIENT_ID) ON DELETE CASCADE,
                         CONSTRAINT INCOME_TYPE_FK FOREIGN KEY (INCOME_TYPE_ID) REFERENCES INCOME_TYPES (INCOME_TYPE_ID),
                         CONSTRAINT INCOME_ASSET_FK FOREIGN KEY (ASSET_ID) REFERENCES ASSETS (ASSET_ID)
);
/

CREATE TABLE EXPENSE_TYPES (
                               EXPENSE_TYPE_ID INTEGER NOT NULL,
                               NAME            VARCHAR2(50 CHAR) NOT NULL,
                               CONSTRAINT EXPENSE_TYPE_PK PRIMARY KEY (EXPENSE_TYPE_ID),
                               CONSTRAINT EXPENSE_TYPE_NAME_UN UNIQUE (NAME)
);
/

CREATE TABLE EXPENSES (
                          EXPENSE_ID      INTEGER NOT NULL,
                          AMOUNT          INTEGER NOT NULL,
                          IS_MANDATORY    NUMBER(1) DEFAULT 0 NOT NULL,
                          CLIENT_ID       INTEGER NOT NULL,
                          EXPENSE_TYPE_ID INTEGER NOT NULL,
                          CONSTRAINT EXPENSE_PK PRIMARY KEY (EXPENSE_ID),
                          CONSTRAINT EXPENSE_AMOUNT_CK CHECK (AMOUNT BETWEEN -999999999 AND -1),
                          CONSTRAINT EXPENSE_MANDATORY_CK CHECK (IS_MANDATORY IN (0, 1)),
                          CONSTRAINT EXPENSE_CLIENT_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (CLIENT_ID) ON DELETE CASCADE,
                          CONSTRAINT EXPENSE_TYPE_FK FOREIGN KEY (EXPENSE_TYPE_ID) REFERENCES EXPENSE_TYPES (EXPENSE_TYPE_ID)
);
/

-- =============================================
-- 5. PRODUCTS & PROVIDERS
-- =============================================

CREATE TABLE PROVIDERS (
                           PROVIDER_ID INTEGER NOT NULL,
                           NAME        VARCHAR2(100 CHAR) NOT NULL,
                           CONSTRAINT PROVIDER_PK PRIMARY KEY (PROVIDER_ID),
                           CONSTRAINT PROVIDER_NAME_UN UNIQUE (NAME)
);
/

CREATE TABLE PRODUCT_TYPES (
                               PRODUCT_TYPE_ID INTEGER NOT NULL,
                               NAME            VARCHAR2(50 CHAR) NOT NULL,
                               CONSTRAINT PRODUCT_TYPE_PK PRIMARY KEY (PRODUCT_TYPE_ID),
                               CONSTRAINT PRODUCT_TYPE_NAME_UN UNIQUE (NAME)
);
/

CREATE TABLE PRODUCTS (
                          PRODUCT_ID         INTEGER NOT NULL,
                          NAME               VARCHAR2(150 CHAR) NOT NULL,
                          AMOUNT             NUMBER(10,2) NOT NULL,
                          START_DATE         DATE NOT NULL,
                          END_DATE           DATE,
                          DOCUMENTATION_URL  VARCHAR2(256 CHAR) NOT NULL,
                          PRODUCT_TYPE_ID    INTEGER NOT NULL,
                          CLIENT_ID          INTEGER NOT NULL,
                          PROVIDER_ID        INTEGER NOT NULL,
                          ARRANGED_BY_ID     INTEGER,
                          CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID),
                          CONSTRAINT PRODUCT_AMOUNT_CK CHECK (AMOUNT BETWEEN 0.00 AND 99999999.99),
                          CONSTRAINT PRODUCT_DATES_CK CHECK (END_DATE IS NULL OR END_DATE > START_DATE),
                          CONSTRAINT PRODUCT_CLIENT_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (CLIENT_ID) ON DELETE CASCADE,
                          CONSTRAINT PRODUCT_TYPE_FK FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPES (PRODUCT_TYPE_ID),
                          CONSTRAINT PRODUCT_PROVIDER_FK FOREIGN KEY (PROVIDER_ID) REFERENCES PROVIDERS (PROVIDER_ID),
                          CONSTRAINT PRODUCT_ADVISOR_FK FOREIGN KEY (ARRANGED_BY_ID) REFERENCES ADVISORS (ADVISOR_ID)
);
/

-- =============================================
-- 6. DOCUMENTS
-- =============================================

CREATE TABLE DOCUMENT_TYPES (
                                DOCUMENT_TYPE_ID INTEGER NOT NULL,
                                NAME             VARCHAR2(50 CHAR) NOT NULL,
                                CONSTRAINT DOCUMENT_TYPE_PK PRIMARY KEY (DOCUMENT_TYPE_ID),
                                CONSTRAINT DOCUMENT_TYPE_NAME_UN UNIQUE (NAME)
);
/

CREATE TABLE DOCUMENTS (
                           DOCUMENT_ID      INTEGER NOT NULL,
                           FILE_NAME        VARCHAR2(255 CHAR) NOT NULL,
                           FILE_PATH        VARCHAR2(512 CHAR) NOT NULL,
                           UPLOADED_AT      DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
                           DOCUMENT_TYPE_ID INTEGER NOT NULL,
                           CLIENT_ID        INTEGER NOT NULL,
                           PRODUCT_ID       INTEGER,
                           CONSTRAINT DOCUMENT_PK PRIMARY KEY (DOCUMENT_ID),
                           CONSTRAINT DOCUMENT_TYPE_FK FOREIGN KEY (DOCUMENT_TYPE_ID) REFERENCES DOCUMENT_TYPES (DOCUMENT_TYPE_ID),
                           CONSTRAINT DOCUMENT_CLIENT_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (CLIENT_ID) ON DELETE CASCADE,
                           CONSTRAINT DOCUMENT_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID) ON DELETE CASCADE
);
/

-- =============================================
-- 7. VIEWS
-- =============================================

CREATE OR REPLACE VIEW V_CLIENT_ADDRESSES AS
SELECT
    C.CLIENT_ID,
    ST_P.NAME AS PERM_STREET,
    A_P.HOUSE_NUMBER AS PERM_HOUSE_NUM,
    A_P.ORIENTATION_NUMBER AS PERM_ORIENT_NUM,
    CI_P.PSC AS PERM_PSC,
    CI_P.NAME AS PERM_CITY,
    ST_C.NAME AS CONT_STREET,
    A_C.HOUSE_NUMBER AS CONT_HOUSE_NUM,
    A_C.ORIENTATION_NUMBER AS CONT_ORIENT_NUM,
    CI_C.PSC AS CONT_PSC,
    CI_C.NAME AS CONT_CITY
FROM CLIENTS C
         JOIN ADDRESSES A_P ON C.PERMANENT_ADDR_ID = A_P.ADDRESS_ID
         JOIN STREETS ST_P ON A_P.STREET_ID = ST_P.STREET_ID
         JOIN CITIES CI_P ON ST_P.CITY_ID = CI_P.CITY_ID
         JOIN ADDRESSES A_C ON C.CONTACT_ADDR_ID = A_C.ADDRESS_ID
         JOIN STREETS ST_C ON A_C.STREET_ID = ST_C.STREET_ID
         JOIN CITIES CI_C ON ST_C.CITY_ID = CI_C.CITY_ID;
/

-- =============================================
-- 8. TRIGGERS (BUSINESS LOGIC)
-- =============================================

CREATE OR REPLACE TRIGGER TRG_ADDRESSES_BU
BEFORE UPDATE ON ADDRESSES
                  FOR EACH ROW
BEGIN
    raise_application_error(-20011, 'Address records are immutable. Create a new record for changes (PP11).');
END;
/

CREATE OR REPLACE TRIGGER TRG_CLIENTS_BIU
BEFORE INSERT OR UPDATE ON CLIENTS
                            FOR EACH ROW
BEGIN
    :NEW.LAST_UPDATE := TRUNC(SYSDATE);
    IF :NEW.BIRTH_DATE > ADD_MONTHS(TRUNC(SYSDATE), -12*18) THEN
        raise_application_error(-20012, 'Client must be at least 18 years old (PP12).');
END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ADVISORS_BIU
BEFORE INSERT OR UPDATE ON ADVISORS
                            FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.MANAGER_ID IS NOT NULL THEN
        raise_application_error(-20002, 'A new advisor cannot have a manager assigned immediately (PP02).');
END IF;
    IF :NEW.MANAGER_ID = :NEW.ADVISOR_ID THEN
        raise_application_error(-20010, 'An advisor cannot be their own manager (PP10).');
END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_INCOMES_BIU
BEFORE INSERT OR UPDATE ON INCOMES
                            FOR EACH ROW
DECLARE
v_linked NUMBER(1);
    v_owner  INTEGER;
BEGIN
    IF :NEW.ASSET_ID IS NOT NULL THEN
SELECT IS_ASSET_LINKED INTO v_linked FROM INCOME_TYPES WHERE INCOME_TYPE_ID = :NEW.INCOME_TYPE_ID;
IF v_linked = 0 THEN
            raise_application_error(-20009, 'This income type cannot be linked to an asset.');
END IF;
SELECT CLIENT_ID INTO v_owner FROM ASSETS WHERE ASSET_ID = :NEW.ASSET_ID;
IF v_owner <> :NEW.CLIENT_ID THEN
            raise_application_error(-20009, 'Income and Asset must belong to the same client.');
END IF;
END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PRODUCTS_BI
BEFORE INSERT ON PRODUCTS
FOR EACH ROW
DECLARE
v_expiry DATE;
    v_current_adv INTEGER;
BEGIN
SELECT ID_CARD_EXPIRY_DATE, ADVISOR_ID INTO v_expiry, v_current_adv FROM CLIENTS WHERE CLIENT_ID = :NEW.CLIENT_ID;
IF v_expiry < SYSDATE THEN
        raise_application_error(-20001, 'Cannot arrange product: Client ID card expired (PP01).');
END IF;
    IF :NEW.ARRANGED_BY_ID IS NOT NULL AND v_current_adv <> :NEW.ARRANGED_BY_ID THEN
        raise_application_error(-20004, 'The arranger must be the client current advisor (PP04).');
END IF;
END;
/

-- =============================================
-- 9. FOREIGN KEY INDEXES (Performance)
-- =============================================

CREATE INDEX IDX_STREET_CITY_FK     ON STREETS (CITY_ID);
/
CREATE INDEX IDX_ADDRESS_STREET_FK  ON ADDRESSES (STREET_ID);
/
CREATE INDEX IDX_CLIENT_ADVISOR_FK  ON CLIENTS (ADVISOR_ID);
/
CREATE INDEX IDX_CLIENT_PERM_ADDR_FK ON CLIENTS (PERMANENT_ADDR_ID);
/
CREATE INDEX IDX_CLIENT_CONT_ADDR_FK ON CLIENTS (CONTACT_ADDR_ID);
/
CREATE INDEX IDX_ADVISOR_MANAGER_FK  ON ADVISORS (MANAGER_ID);
/
CREATE INDEX IDX_ASSET_CLIENT_FK    ON ASSETS (CLIENT_ID);
/
CREATE INDEX IDX_ASSET_TYPE_FK      ON ASSETS (ASSET_TYPE_ID);
/
CREATE INDEX IDX_INCOME_CLIENT_FK   ON INCOMES (CLIENT_ID);
/
CREATE INDEX IDX_INCOME_TYPE_FK     ON INCOMES (INCOME_TYPE_ID);
/
CREATE INDEX IDX_INCOME_ASSET_FK    ON INCOMES (ASSET_ID);
/
CREATE INDEX IDX_EXPENSE_CLIENT_FK  ON EXPENSES (CLIENT_ID);
/
CREATE INDEX IDX_EXPENSE_TYPE_FK    ON EXPENSES (EXPENSE_TYPE_ID);
/
CREATE INDEX IDX_PRODUCT_CLIENT_FK  ON PRODUCTS (CLIENT_ID);
/
CREATE INDEX IDX_PRODUCT_TYPE_FK    ON PRODUCTS (PRODUCT_TYPE_ID);
/
CREATE INDEX IDX_PRODUCT_PROVIDER_FK ON PRODUCTS (PROVIDER_ID);
/
CREATE INDEX IDX_PRODUCT_ARRANGER_FK ON PRODUCTS (ARRANGED_BY_ID);
/
CREATE INDEX IDX_DOCUMENT_TYPE_FK    ON DOCUMENTS (DOCUMENT_TYPE_ID);
/
CREATE INDEX IDX_DOCUMENT_CLIENT_FK  ON DOCUMENTS (CLIENT_ID);
/
CREATE INDEX IDX_DOCUMENT_PRODUCT_FK ON DOCUMENTS (PRODUCT_ID);
/

-- =============================================
-- 10. SEARCH INDEXES (User Experience)
-- =============================================

CREATE INDEX IDX_CLIENT_LAST_FIRST  ON CLIENTS (LAST_NAME, FIRST_NAME);
/
CREATE INDEX IDX_ADVISOR_LAST_FIRST ON ADVISORS (LAST_NAME, FIRST_NAME);
/

-- =============================================
-- 11. ID GENERATION (SEQUENCES & AUTO-INC)
-- =============================================

CREATE OR REPLACE TRIGGER TRG_INCOMES_ID BEFORE INSERT ON INCOMES FOR EACH ROW WHEN (NEW.INCOME_ID IS NULL)
BEGIN :NEW.INCOME_ID := BUDGET_ITEM_SEQ.NEXTVAL; END;
/

CREATE OR REPLACE TRIGGER TRG_EXPENSES_ID BEFORE INSERT ON EXPENSES FOR EACH ROW WHEN (NEW.EXPENSE_ID IS NULL)
BEGIN :NEW.EXPENSE_ID := BUDGET_ITEM_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE CITY_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_CITY_ID BEFORE INSERT ON CITIES FOR EACH ROW WHEN (NEW.CITY_ID IS NULL) BEGIN :NEW.CITY_ID := CITY_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE STREET_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_STREET_ID BEFORE INSERT ON STREETS FOR EACH ROW WHEN (NEW.STREET_ID IS NULL) BEGIN :NEW.STREET_ID := STREET_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE ADDR_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_ADDR_ID BEFORE INSERT ON ADDRESSES FOR EACH ROW WHEN (NEW.ADDRESS_ID IS NULL) BEGIN :NEW.ADDRESS_ID := ADDR_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE ADVISOR_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_ADVISOR_ID BEFORE INSERT ON ADVISORS FOR EACH ROW WHEN (NEW.ADVISOR_ID IS NULL) BEGIN :NEW.ADVISOR_ID := ADVISOR_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE CLIENT_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_CLIENT_ID BEFORE INSERT ON CLIENTS FOR EACH ROW WHEN (NEW.CLIENT_ID IS NULL) BEGIN :NEW.CLIENT_ID := CLIENT_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE ASSET_TYPE_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_ASSET_TYPE_ID BEFORE INSERT ON ASSET_TYPES FOR EACH ROW WHEN (NEW.ASSET_TYPE_ID IS NULL) BEGIN :NEW.ASSET_TYPE_ID := ASSET_TYPE_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE ASSET_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_ASSET_ID BEFORE INSERT ON ASSETS FOR EACH ROW WHEN (NEW.ASSET_ID IS NULL) BEGIN :NEW.ASSET_ID := ASSET_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE INCOME_TYPE_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_INCOME_TYPE_ID BEFORE INSERT ON INCOME_TYPES FOR EACH ROW WHEN (NEW.INCOME_TYPE_ID IS NULL) BEGIN :NEW.INCOME_TYPE_ID := INCOME_TYPE_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE EXPENSE_TYPE_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_EXPENSE_TYPE_ID BEFORE INSERT ON EXPENSE_TYPES FOR EACH ROW WHEN (NEW.EXPENSE_TYPE_ID IS NULL) BEGIN :NEW.EXPENSE_TYPE_ID := EXPENSE_TYPE_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE PROVIDER_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_PROVIDER_ID BEFORE INSERT ON PROVIDERS FOR EACH ROW WHEN (NEW.PROVIDER_ID IS NULL) BEGIN :NEW.PROVIDER_ID := PROVIDER_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE PRODUCT_TYPE_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_PRODUCT_TYPE_ID BEFORE INSERT ON PRODUCT_TYPES FOR EACH ROW WHEN (NEW.PRODUCT_TYPE_ID IS NULL) BEGIN :NEW.PRODUCT_TYPE_ID := PRODUCT_TYPE_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE PRODUCT_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_PRODUCT_ID BEFORE INSERT ON PRODUCTS FOR EACH ROW WHEN (NEW.PRODUCT_ID IS NULL) BEGIN :NEW.PRODUCT_ID := PRODUCT_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE DOCUMENT_TYPE_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_DOCUMENT_TYPE_ID BEFORE INSERT ON DOCUMENT_TYPES FOR EACH ROW WHEN (NEW.DOCUMENT_TYPE_ID IS NULL) BEGIN :NEW.DOCUMENT_TYPE_ID := DOCUMENT_TYPE_SEQ.NEXTVAL; END;
/

CREATE SEQUENCE DOCUMENT_SEQ START WITH 1;
/
CREATE OR REPLACE TRIGGER TRG_DOCUMENT_ID BEFORE INSERT ON DOCUMENTS FOR EACH ROW WHEN (NEW.DOCUMENT_ID IS NULL) BEGIN :NEW.DOCUMENT_ID := DOCUMENT_SEQ.NEXTVAL; END;
/